# 开发环境配置
env: 'development'
app:
  port: 3002
  logger:
    # 项目日志存储路径，相对路径，项目下的路径，如：src下的log，src/logs
    dir: 'logs'

# 数据库配置
db:
  mysql:
    host: '127.0.0.1'
    username: 'kamtao'
    password: 'tao19981117'
    database: 'lc'
    port: 3306
    charser: 'utf8mb4'

# jwt 配置
jwt:
  secretkey: 'zANDwNQVFzxlfG9myPxVWAkq4iXJEPhI'
  expiresin: '1h'
  refreshExpiresIn: '2h'

# 权限 白名单配置
perm:
  router:
    whitelist:
      [
        { path: '/api/register', method: 'POST' },
        { path: '/api/login', method: 'POST' },
        { path: '/api/perm/{id}', method: 'GET' },
        { path: '/api/oss/upload', method: 'POST' },
      ]

# 用户相关
# 初始密码， 重置密码
user:
  initialPassword: 'Q123456'
